### ISSUE TITLE
Missing hardware documentation

### ISSUE THREAD

**Issue by zbrozek** [DFRobot/DFRobot_BME280#1]
It used to be in this repository but was deleted with this commit:
https://github.com/DFRobot/DFRobot_BME280/commit/f73954b87ebb3a72268579e742a3143ffa0b6aee

It can still be accessed here:
https://github.com/DFRobot/DFRobot_BME280/tree/3e0333b58833ff4935715c700f85bb0feaff5005

Would be nice to bring it back.

**Comment by qsjhyy** [comment]
Due to format requirements, hardware documentation will not be uploaded to Github. 
Welcome to the official DFRobot Wiki:
https://wiki.dfrobot.com
Check the related hardware documentation, thank you.
