### ISSUE TITLE
library.properties file missing

### ISSUE THREAD

**Issue by yannisant** [DFRobot/DFRobot_BME280#2]
Hello,

I am trying to upload the library for the [DFRobot_BME280] to the Arduino online editor and I get an error message about the library.properties file missing. Can you please help? Do I generate this file? Or can I find it?

Kind regards,

Yannis

**Comment by qsjhyy** [comment]
The library properties file has been added successfully, thanks for your suggestion!
And, after we standardize all the formats, we upload it to the Arduino online editor.
